### ISSUE TITLE
Clone Button

### ISSUE THREAD

**Issue by Basti77** [faebser/raspberry-pi-usb-cloner#2]
Hello and thank you for your work.
That's exactly what I'm looking for,

However, the "clone" button has no function.
I have already made all the files executable and started the script with sudo.

The Pi also has an LCD display with touch screen for offline usage.

**Comment by faebser** [comment]
hi,

you mean the clone button in the web ui? Did you follow the installation instructions?

**Comment by Basti77** [comment]
Thank you for your answer.
Yes, exactly, the button in the web UI.
I have the component "dcfldd" installed.
still no function. :(

**Comment by faebser** [comment]
Can you check the developer console in your browser? Maybe it outputs a error if you press the button?

**Comment by Basti77** [comment]
yes there are some.
Chrome:

Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:6 Uncaught ReferenceError: Mustache is not defined
    at main.js:6
    at main.js:120
/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by faebser** [comment]
I added the missing file. Can you please update your raspberry and let me know if it works?

thanks

**Comment by Basti77** [comment]
Now it works!
Thank you.
